### ISSUE TITLE
[feat] Support templated variables pointing to other templated variables

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#101]
Allow users to point a templated variable at another templated variable to avoid having to duplicate values.

There could be scenarios where different workspaces have different names for the same vale or a user might want to have the same global value he can use for all projects which other user might not have the same access.

Links #99

**Comment by mhmdkrmabd** [comment]
- Now the app supports nested variables.
- User can now in a variable's value point to another variable - their scope should be intersected or the pointed-at variable's scope is `all workspaces` -.
- The nested/pointed-at variable can also contain nested variables as well.

Doing further tests.
