### ISSUE TITLE
[bug] Mac .pkg installer is not signed properly

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#103]
From the electron-installer docs, we're missing the right certs 

> If you are wrapping app to installer (pkg), you need to have INSTALLER ID identity in your keychain or provide according CSC_INSTALLER_LINK and CSC_INSTALLER_KEY_PASSWORD.

**Comment by digiserg** [comment]
I've added the certs to the github actions. We'll know if they worked on the next release.

**Comment by millerjp** [comment]
@digiserg could you retest please on latest beta

**Comment by digiserg** [comment]
It's not working still. I'm looking into it.

**Comment by digiserg** [comment]
Refers to https://github.com/electron-userland/electron-builder/issues/4710
