### ISSUE TITLE
cqlsh does not work on Windows 11

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#105]
![image](https://github.com/user-attachments/assets/57b2c8de-576c-439c-9317-6e2f5b9b0c41)

it seems to crash on backend

**Comment by digiserg** [comment]
@mhmdkrmabd I don't have a windows to play with. This is what I've done but it's not enough

https://github.com/axonops/axonops-workbench-cqlsh/compare/main...105-cqlsh-does-not-work-on-windows-11

**Comment by mhmdkrmabd** [comment]
Investigating on Windows 11

**Comment by mhmdkrmabd** [comment]
Issue has been solved, doing further tests

**Comment by digiserg** [comment]
Tested, it's working now. Thanks.
