### ISSUE TITLE
Linux .deb install issues

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#110]
There are a few issues with the install on Debian-based systems
- The app installs to `/opt/AxonOpsCassandra`, should that be `/opt/AxonOpsWorkbench`?
- The menu entry has no icon and has the name `AxonOpsCassandra`. It needs an icon and it should be named `AxonOps Workbench`
- The app's icon is installed in the wrong location, it is being put in `/usr/share/icons/hicolor/0x0/apps/axonops-workbench-cassandra.png` but it should be in the folder for the appropriate image size
- Uninstalling the package gives these warning messages:
```
update-alternatives: warning: alternative /opt/AxonOpsCassandra/axonops-workbench-cassandra (part of link group axonops-workbench-cassandra) doesn't exist; removing from list of alternatives
update-alternatives: warning: /etc/alternatives/axonops-workbench-cassandra is dangling; it will be updated with best choice
```

**Comment by millerjp** [comment]
@rgooding No - AxonOpsWorkbench is not the correct dir as there will be different ones for other Tech we support in workbench. It could be AxonOpsWorkbenchCassandra - but definitely not AxonOpsWorkbench.

@mhmdkrmabd @digiserg Regarding names - it should be AxonOps Workbench for Cassandra.

**Comment by digiserg** [comment]
I see the problem with the icon, the filename does not contain the resolution. I'll sort this out.

> Linux icon set will be generated automatically based on the macOS icns file or common icon.png.
> 
> Or you can put them into the build/icons directory if you want to specify them yourself. The filename must contain the size (e.g. 256x256.png) of the icon). Recommended sizes: 16, 32, 48, 64, 128, 256 (or just 512).
