### ISSUE TITLE
[feat] Only display Test Connection when its necessary

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#115]
We currently display test connection all the time -  this isnt necessary.

<img width="439" alt="Screenshot 2024-07-16 at 11 30 43" src="https://github.com/user-attachments/assets/2d405661-4f26-441a-be92-10526e0e4a3e">

We should only display it 
1 - for the first time a cluster connection is created
2 - if the cluster connection details have changed
3 - if we get a connection error

We will need to store this state in the OS keychain for the cluster to know when and when not to display the test connection

**Also - we should always display the  test connection option under  the connection settings**

**Comment by millerjp** [comment]
@mhmdkrmabd if this is too complex or likely to cause a lot of testing, we can move this to next release

**Comment by mhmdkrmabd** [comment]
@millerjp I prefer to move this to the next release as it needs many important changes and tests as well
