### ISSUE TITLE
When right clicking over connected cluster icon - display option to disconnect

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#116]
<img width="615" alt="Screenshot 2024-07-16 at 11 47 24" src="https://github.com/user-attachments/assets/99ac7300-5554-4222-9c3f-ee215c6881f3">

**Comment by mhmdkrmabd** [comment]
![Image](https://github.com/user-attachments/assets/ddcf9efc-c880-4029-b80b-9800858a67be)

https://github.com/user-attachments/assets/ddcf9efc-c880-4029-b80b-9800858a67be
