### ISSUE TITLE
No keyring available in Ubuntu

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#118]
<img width="804" alt="image" src="https://github.com/user-attachments/assets/614fe0fa-c24e-4c03-8ed6-1035721587c8">

![image](https://github.com/user-attachments/assets/a7dae299-f165-490c-81ba-919d5acafd6a)

**Comment by mhmdkrmabd** [comment]
@digiserg is everything fine to close this issue?

**Comment by digiserg** [comment]
Tested in tag 0.1.0-internal-20240725

It looks good. Closing.
