### ISSUE TITLE
Add OS to build artefacts

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#121]
As @rgooding pointed out, the file names may not easily identify the OS they were built for and we should add it to the file names:

```
AxonOpsCassandra-0.1.0-internal-20240716-arm64.pkg -> AxonOpsCassandra-0.1.0-internal-20240716-mac-arm64.pkg
```

This is easy to do with a macro: https://www.electron.build/file-patterns#file-macros

**Comment by millerjp** [comment]
@digiserg also - we should populate this stuff also
https://www.electron.build/api/electron-builder#AppInfo
