### ISSUE TITLE
Use `docker compose` instead of `docker-compose` when available

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#124]
It does not work in rocky linux with docker-ce. `docker-compose` not available

**Comment by digiserg** [comment]
A workaround I used for now is I created this script in the path `/usr/bin/docker-compose`

```
#!/bin/bash
docker compose $@
```

**Comment by millerjp** [comment]
@digiserg I think we will just add documentation for this
@mhmdkrmabd I think we will add a link to the docs somewhere in the app explaning how to setup the sandbox and docker etc..

**Comment by mhmdkrmabd** [comment]
@millerjp @digiserg now by default the app will attempt to use `docker compose`, if something went wrong then it'll switch to `docker-compose`, if none of them exist the app will give feedback to the user as usual
