### ISSUE TITLE
do not try to change permissions

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#132]
<img width="639" alt="image" src="https://github.com/user-attachments/assets/f71edde8-ff1a-402f-bbc0-9cc013d773f5">

the app should never try to modify files or change permissions

**Comment by mhmdkrmabd** [comment]
@digiserg we execute `chmod +x` before running any binary to make sure it's executable, is this step not necessary with the new build approach? I believe this step doesn't throw an error if something went wrong

**Comment by mhmdkrmabd** [comment]
https://github.com/search?q=repo%3Aaxonops%2Faxonops-workbench-cassandra%20chmod&type=code

**Comment by digiserg** [comment]
It's not, please remove the chmod. Remember users will not have permissions to do this.

**Comment by mhmdkrmabd** [comment]
@digiserg  change mode commands have been removed.
