### ISSUE TITLE
[bug] Alert the user if docker is not running when creating or starting a sandbox cluster

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#139]
When I try to create a sandbox on a desktop where docker has not been installed I get alerted. But if docker is installed but not running (default in windows it seems) I get `unexpected error` instead. 

We should alert the end user if the docker server/daemon is not running.

Not - **only** do this as a pre-check to invoking the docker commands. It is not necessary to have docker running to use the app in BAU fashion.

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
@digiserg so on all OSes if `docker` is not installed or missing the user will get an error feedback:
![Image](https://github.com/user-attachments/assets/fe1eb0eb-abbd-430d-bc77-ef3a2e157637)

On Linux and macOS the up/down commands won't work if `docker-demon` is not running:
![Image](https://github.com/user-attachments/assets/6c5d6a1d-98d4-4fd6-8c67-baf5ee5c692e)
Is this error feedback missing on Windows?

**Comment by mhmdkrmabd** [comment]
![Image](https://github.com/user-attachments/assets/28fc850a-b31b-41d6-80b0-3de0a4a4c2f6)
