### ISSUE TITLE
Cannot delete a sandbox

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#140]
- Create a sandbox
- Start it up
- Go back Home
- Enter Sandbox again
- Try to delete it

https://github.com/user-attachments/assets/7787c7bc-8443-4462-9247-bdb1e2cbde2e

**Comment by mhmdkrmabd** [comment]
@digiserg so if there's a status for the docker project - started and connected or failed to start - it won't be deleted? let me check that and I'll commit changes

**Comment by digiserg** [comment]
Maybe we need an option to stop the sandbox
