### ISSUE TITLE
[feat] Add option to signout of AxonOps cloud

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#158]
We need to have an option to signout of AxonOps. To do this we need to delete the cookies in the app from axonops.cloud

**Comment by millerjp** [comment]
Maybe add a Sign Out of AxonOps option here under File -> Sign out of AxonOps

![Image](https://github.com/user-attachments/assets/23d31c8a-7e91-412e-a553-20fb31d92daf)

**Comment by mhmdkrmabd** [comment]
Added the ability to logout/signout of AxonOps Cloud
![Image](https://github.com/user-attachments/assets/44aae71c-1293-45ec-8c2e-fa0711bfffc5)
