### ISSUE TITLE
Have 4 CQLSH connections when should have 1

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#161]
<img width="1293" alt="Screenshot 2024-07-29 at 12 23 40" src="https://github.com/user-attachments/assets/f2966ea4-c0db-4468-8382-e72c334fac10">

We should be lazily initiatlising the second CQLSH for the basic terminal someone clicks on the switch terminal window.

**Comment by mhmdkrmabd** [comment]
@millerjp it seems the app doesn't start two instances of the cqlsh tool, but the tool itself runs two processes:


![Image](https://github.com/user-attachments/assets/32e09596-5a78-46c8-a385-b7cc3a2c52fd)

Checking the original cqlsh tool shipped with Cassandra

**Comment by mhmdkrmabd** [comment]
@millerjp it's a `pyinstaller` matter:
https://github.com/pyinstaller/pyinstaller/issues/2483#issuecomment-284224403

The recommendation is keep the cqlsh tool as one file, the other process is very low-memory usage and only to clear temp files of the binary
