### ISSUE TITLE
[bug] Wrong default path for workspaces on Mac

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#175]
<img width="521" alt="image" src="https://github.com/user-attachments/assets/6302c447-9ec8-45df-bcfb-a5b07f4fe970">

The default path is wrong for workspaces

It should be

```
~/Library/AxonOps Workbench/
```

**Comment by mhmdkrmabd** [comment]
On Linux the path is fine, will check on macOS

![Image](https://github.com/user-attachments/assets/2601b102-15ec-4218-ae73-558a1cf7514b)

**Comment by mhmdkrmabd** [comment]
To be reviewed in the next PR

**Comment by millerjp** [comment]
@digiserg to be crystal clear - workspaces and be anywhere on the OS. They do not have to be in the default location.

@mhmdkrmabd we should only add workspaces to the default location if the users chooses not to put it somewhere else. Please when they checkout a workspace from Git it could be anywhere on the filesystem and the users should be able to import it and use it from that defined location.

**Comment by mhmdkrmabd** [comment]
Everything is fine one, in one of the releases on macOS the app's data placed in the home directory outside the folder `.axonops-` now everything should be fine, this can be closed
