### ISSUE TITLE
[feat] Add stop button to docker projects

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#177]
<img width="536" alt="image" src="https://github.com/user-attachments/assets/11bc61a2-bcce-4545-8cb6-eaa0389157c0">

it would be good to have a stop button for docker projects

**Comment by mhmdkrmabd** [comment]
You can actually stop/down the docker project using the `X` button at the top right of the work area, or right click the icon in the left panel and close workarea (disconnect), pointing at something else?

**Comment by digiserg** [comment]
I never even noticed! I think a STOP button next to START would make more sense
