### ISSUE TITLE
[feat] Increase default size of AI window

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#187]
Its too small - increase its default size by 50% - it cuts of the MFA screen and the chat window minimum size. Its too small for any useage with the current size - you are always making it bigger to use the chat 

<img width="574" alt="Screenshot 2024-08-05 at 10 39 00" src="https://github.com/user-attachments/assets/e64dbda4-8a73-499c-899c-4ed0bb8a920e">

**Comment by mhmdkrmabd** [comment]
Increased to be 450px instead of 350px
