### ISSUE TITLE
Separate Sandbox and Workspaces

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#189]
Sandbox tile and Workspace tile are in the same view. As a first time user of the Workbench, it was confusing to see them in one place.

![image](https://github.com/user-attachments/assets/57443fde-edb4-43bb-a889-568d38e7fa67)

Can we have one of the two suggestions below?

- Create two sections in the view for Workspaces and Sandboxes - either horizontal or vertical sections
- Create separate pages for Workspaces and Sandboxes, with navigation buttons on the left vertical bar

**Comment by millerjp** [comment]
@hshimizu No - we wont do this. The current view is fine.
