### ISSUE TITLE
Sandbox panel creation and deletion

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#190]
"Docker Projects (Sandbox)" is automatically created when I create a Workspace. I then create another workspace but Sandbox does not created with the second Workspace. This is a confusing behaviour.

I then delete the first Workspace, but the Sandbox is not deleted until I delete the second Workspace.

Why does the Sandbox tile automatically get created when I create the first Workspace, but not the second? It feels like the the Sandbox created as part of the first Workspace creation are associated, but in fact, there is no association.

I would prefer to have a dedicated button to create Sandboxes than for it to be created when I create the first Workspace.

**Comment by millerjp** [comment]
@hshimizu the behaviour of the app is the the "Sandbox"/"Local Clusters" is a local workspace in itself. There is only ever 1 sandbox workspace. The app does not have the ability to create local clusters within user defined workspaces.
