### ISSUE TITLE
[feat] Do not use Docker or Sandbox text in UX - change wording to just Local Clusters

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#191]
Docker is a trademarked commercial company. We should avoid using the name Docker in this product.

![image](https://github.com/user-attachments/assets/4f377197-2171-4e3e-84d8-ff9a24a871cd)

"Docker Projects (Sandbox)" -> "Local Sandboxes"

**Comment by millerjp** [comment]
@mhmdkrmabd I think we need to just say "Local Clusters" and remove the "Sandbox" reference. Can you updat the UX to no longer use the text sandbox or docker. Make sure to update the translations.

**Comment by mhmdkrmabd** [comment]
@millerjp working on that

**Comment by mhmdkrmabd** [comment]
@millerjp @hshimizu 

https://github.com/user-attachments/assets/37dbbb16-0639-467e-aaa1-586e52ece573

**Comment by millerjp** [comment]
looks great @mhmdkrmabd
