### ISSUE TITLE
[feat] When the app is launched for the first time users need to be able to just create a sandbox cluster

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#212]
In the UI when the app is launched for the first time we see this screen:
<img width="1707" alt="Screenshot 2024-08-11 at 11 12 03" src="https://github.com/user-attachments/assets/015f16cf-7f70-4fa8-acb9-f7a664816ed8">

However, there is no indication of local/sandbox clusters.

Add another OR option to the screen "Create Local Cluster" which then moves you into the sandbox/local cluster feature.

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
![Image](https://github.com/user-attachments/assets/cbe2b97a-1fcf-4638-835c-997848a9e998)
