### ISSUE TITLE
[bug] Query copy button / paste not working

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#216]
![image](https://github.com/user-attachments/assets/ed5b895a-0d14-449d-90e8-54c1f7f9b3bf)

![image](https://github.com/user-attachments/assets/19ea35ee-3688-4a30-837b-fe8b6c07eab2)

**Comment by millerjp** [comment]
@mhmdkrmabd I cant reproduce this on Mac. Can you check on Windows?
