### ISSUE TITLE
[bug] Table description shows incorrect output

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#218]
![image](https://github.com/user-attachments/assets/b3b02c1b-0f90-4da2-9169-a47294067636)

CREATE TABLECREATE KEYSPACE hayato WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

**Comment by mhmdkrmabd** [comment]
Investigating that

**Comment by mhmdkrmabd** [comment]
Confirmed, it's only happen if the table and the keyspace have the same name, thank you @hshimizu, working on that

**Comment by mhmdkrmabd** [comment]
Fixed, everything should be fine after the next PR
