### ISSUE TITLE
Incorrect logs directory

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#22]
The logs directory is set as

```
this.loggingFilesPath = Path.join((extraResourcesPath != null ? Path.join(extraResourcesPath) : Path.join(__dirname, '..', '..')), 'data', 'logging')
```

This is not correct. I should point to `app.getPath('logs')` as this is not working at least for Mac. I haven't tested others yet.

The correct paths are:

on Linux: ~/. config/{app name}/logs/main.log.
on macOS: ~/Library/Logs/{app name}/main.log.
on Windows: %USERPROFILE%\AppData\Roaming\{app name}\logs\main.log.

**Comment by digiserg** [comment]
Tested on Mac where it looks good

**Comment by millerjp** [comment]
@digiserg @mhmdkrmabd can we close this now?
