### ISSUE TITLE
[feat] Cluster Diff should show the timestamp of "Old"

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#221]
What is "Old"? This requires the timestamp of when the "Old", and "New" were recorded.

![image](https://github.com/user-attachments/assets/6995695c-ec4c-4354-adf8-9fc7a63f671a)

**Comment by millerjp** [comment]
@mhmdkrmabd we probably need to add some data to the JSON with the UTC timestamp of when it was taken (and then adjust to the users local TZ)

**Comment by hshimizu** [comment]
Also "Old" to "Previous"

**Comment by mhmdkrmabd** [comment]
@hshimizu good point for sure, "Previous" is more convenient than "Old" - it refers to the previous loaded metadata, where the right side is the "New" loaded one -

**Comment by mhmdkrmabd** [comment]
> [@mhmdkrmabd](https://github.com/mhmdkrmabd) we probably need to add some data to the JSON with the **UTC** timestamp of when it was taken and then adjust to the users local TZ

Working on this feature

**Comment by mhmdkrmabd** [comment]
![Image](https://github.com/user-attachments/assets/7bbcd92c-2642-4810-a627-4100d723e6dc)

**Comment by mhmdkrmabd** [comment]
@millerjp @hshimizu 


https://github.com/user-attachments/assets/ff4aae7e-360e-48c8-ba1f-f550a7bbe0b9
