### ISSUE TITLE
[feat] Rename Cluster Diff to Schema Diff

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#223]
![image](https://github.com/user-attachments/assets/6c2f1c84-4130-4d03-ad8e-93b70d18110a)

Cluster Diff shows the schema differences, not the cluster configuration.

This needs to say CQL Schema Diff. I would prefer it if it shows the history of changes, and being able to diff between the changes.

![image](https://github.com/user-attachments/assets/080924b2-d13e-4601-956b-407a244fe02f)

Also "New" -> "Current"

**Comment by millerjp** [comment]
@hshimizu we will rename it to Schema Diff
