### ISSUE TITLE
Rename "SWITCH TERMINAL" button

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#225]
![image](https://github.com/user-attachments/assets/cbe7d222-77be-4436-8f09-1cb149f8d419)

In the notebook view, the blue button should show "Terminal View".

When in the CQLSH Terminal view, the button should show "Notebook View"

**Comment by millerjp** [comment]
@hshimizu no - our terminal is not a notebook. A notebook is something else - we will bring this feature in later releases.
