### ISSUE TITLE
[bug] Remove "Is CQL Compatible" attribute from table tree

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#226]
![image](https://github.com/user-attachments/assets/b3faab6f-c3c2-40d4-afba-103a20f7f8e7)

I'm not sure what this means. Does it mean CQL version compatibility with the version of Cassandra?

If so, it could say "CQL Version Compatible"

**Comment by mhmdkrmabd** [comment]
@millerjp 
https://docs.datastax.com/en/developer/python-driver/3.29/api/cassandra/metadata/index.html

![Image](https://github.com/user-attachments/assets/ce761ea3-8ec6-4b50-860a-f34c5ec530f7)
