### ISSUE TITLE
[bug] Sandbox/local clusters are no longer available

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#227]
The ability to add local clusters has been removed! This option seems to no longer exist on 0.1.1-internal-20240811

<img width="331" alt="Screenshot 2024-08-12 at 13 45 15" src="https://github.com/user-attachments/assets/ee8a215a-9344-49b5-93ec-68d6fb4703e0">
<img width="1321" alt="Screenshot 2024-08-12 at 13 44 56" src="https://github.com/user-attachments/assets/7a3501d3-2392-4bb2-9221-096496728a49">

**Comment by millerjp** [comment]
@mhmdkrmabd ok - this has been moved to being enabled/disabled by a system setting. Can you make sure this is enabled by default.

**Comment by mhmdkrmabd** [comment]
It's now enabled by default
