### ISSUE TITLE
[bug] Windows: CQL query results are not displayed correctly

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#230]
When I run a CQL query on Windows the results are not being displayed correctly.
The table queried in the screenshot below has this schema: 
```
CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
)
```

It looks like it has taken one of the values as the field names then only displayed data for the first row:
![Screenshot 2024-08-12 at 13 19 06](https://github.com/user-attachments/assets/d789962d-9a7c-4f62-9da8-edefc53a5084)

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
@millerjp @rgooding, the cause of the issue - on Windows - is the addition of escape character - backslash - more than needed, causes a bad JSON structure, handled that, that's the final result:

![Image](https://github.com/user-attachments/assets/a3e916c3-e6e7-4f8c-b5e7-ef3ae5c51d22)
