### ISSUE TITLE
[bug] Missing sha256sum hashes for some files

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#234]
There are no sha256sum files being generated for the .deb package or the Windows .zip version. These should be added so that users can verify the downloads as with all other installer types.

**Comment by digiserg** [comment]
This is usually not required as package managers do it for you but it's not a big deal to add it. PR opened. 

```
~$ rpm --checksig -v AxonOps.Workbench-0.1.1-internal-20240813-linux-x86_64.rpm
AxonOps.Workbench-0.1.1-internal-20240813-linux-x86_64.rpm:
    Header SHA256 digest: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: OK
    MD5 digest: OK
```
