### ISSUE TITLE
[bug] macOS: Close Window minimises instead of closing

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#236]
In macOS applications you should be able to close a window by pressing Cmd+w, however when I do this with the workbench app it minimises instead of closing. I also see that there is a `Close Window` menu item, which also minimises the window instead of closing it.

**Comment by millerjp** [comment]
@rgooding on MacOS cmd + Q quits. The behaviour for closing windows on workbench is similar to lots of apps on MacOS. eg Slack. We wont fix this. Thanks!

**Comment by rgooding** [comment]
@millerjp Slack does not minimise when you press Cmd+w, it closes the window. That is a different operation and we are breaking Apple's UI guidelines by minimising.
