### ISSUE TITLE
[feat] TLS configuration: rename Certificate File to CA Certificate File

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#239]
The caption `Certificate File` is ambiguous on the field where you select the CA certificate for TLS connections. It could mean the client certificate or the CA certificate so we should clarify this by changing the caption.

**Comment by millerjp** [comment]
@digiserg can you have a look at this and check what @rgooding is describing as you have been closest to the TLS/SSH stuff.

**Comment by digiserg** [comment]
@mhmdkrmabd I have tested this in the latest versions from my M2 mac and it works fine. However, it doesn't seem to work for @rgooding when using an intel Mac. Would you be able to have a look?

**Comment by millerjp** [comment]
@digiserg was that comment meant for this issue? I dont understand what you tested as this is renaming the input text boc label?
