### ISSUE TITLE
[feat] Add progress dialog when CQL queries being executed to provide feed back to users

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#240]
Sometime CQL queries can take long and there are some perf issues noted in #231 which still need to be investigated.

Add a progress dialog of some sort when CQL queries are being executed and move the abort query option to this.

**Comment by mhmdkrmabd** [comment]
This requires to move part of the execution process to be in the background. Working on that

**Comment by mhmdkrmabd** [comment]
@mhmdkrmabd now the results of the execution is showing much faster than before, beside providing a feedback on which statement is being executed including a loading animation

https://github.com/user-attachments/assets/a7cf6b0c-17ec-4eaf-90cf-f9ba398931dd
