### ISSUE TITLE
[bug] Unable to connect to a cluster using mTLS

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#241]
I have only tested this on macOS so the results may be different on other OSes.

Attempting to connect to a cluster that uses mTLS does not work at all. I have supplied the correct hostname, port and certificates but when I click `Test Connection` it just hangs and gives me no feedback. If the connection failed for any reason I would expect to see an error message but nothing appears, the spinner just stays until I manually cancel it.

Changing the "Validate files" switch does not appear to make any difference (what does this switch do anyway? is this enabling/disabling certificate verification? It needs a better name because nobody will know what it does!)

I can connect to this cluster successfully using `openssl s_client` and using `cqlsh` from the command line

**Comment by digiserg** [comment]
<img width="177" alt="image" src="https://github.com/user-attachments/assets/ee92e5ab-8a79-4826-9abf-7d56c252c8ca">
I tested it on tag `0.1.0-internal-20240805` and it works for me. I'll test the latest versions shortly.

**Comment by mhmdkrmabd** [comment]
@digiserg am tuned for your feedback

**Comment by mhmdkrmabd** [comment]
This is related to #233, will be tested after the new PR
