### ISSUE TITLE
[feat] Keyboard shortcuts for zoom do not work on mac/windows and use the wrong keys on mac

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#242]
On Linux the zoom in, out and reset work perfectly when using the keyboard shortcuts (Ctrl Shift +, Ctrl Shift -, Ctrl Shift 0).
On Windows and Mac only the zoom in (Ctrl Shift +) works, the other shortcuts do nothing.
On macOS the keyboard shortcuts should use Cmd instead of Ctrl as this is the standard in macOS GUI applications, so the shortcuts should be Cmd Shift +, Cmd Shift - and Cmd Shift 0.

**Comment by millerjp** [comment]
@rgooding we dont support zooming yet. We may look at this post initial release.

**Comment by millerjp** [comment]
<img width="415" alt="Screenshot 2024-08-12 at 16 55 33" src="https://github.com/user-attachments/assets/466d1292-6331-429e-87ec-24b08b3d36b8">

**Comment by mhmdkrmabd** [comment]
Confirmed that issue, working on it
