### ISSUE TITLE
[feat] About screen does not tell you about the application

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#243]
The `About` dialog in an application is supposed to be just that - it tells you about the application, we seem to have missed that part when designing ours!
The first thing I would expect to see when opening the `About` dialog is something showing the name of the application, the company who produced it, the copyright year and most importantly the version number.

<img width="386" alt="Screenshot 2024-08-12 at 16 27 41" src="https://github.com/user-attachments/assets/9091f46f-0f3c-43e8-bfe9-9871220190da">

<img width="448" alt="Screenshot 2024-08-12 at 16 27 35" src="https://github.com/user-attachments/assets/0d3b97ee-7c27-4b8c-a12d-e4116d3c8476">

**Comment by millerjp** [comment]
@rgooding this is done here 
<img width="315" alt="Screenshot 2024-08-12 at 16 26 22" src="https://github.com/user-attachments/assets/10496795-6d85-4863-9aa5-d1d1e86d364d">

@mhmdkrmabd do you have any ideas on how we could line these both up. Could we use About in the menu bar to launch our about dialog?

**Comment by mhmdkrmabd** [comment]
@millerjp 


![Image](https://github.com/user-attachments/assets/be8c1e51-d751-41de-975b-0a2de41126f2)
