### ISSUE TITLE
[bug] macOS: Restart just minimises the application

### ISSUE THREAD

**Issue by rgooding** [axonops/axonops-workbench-cassandra#244]
When I try to use the Restart menu option to restart the application it just minimises and does not exit or restart. This only happens on macOS, it seems to work correctly on Linux and Windows.

If I subsequently use the Quit menu item to quit the application it then relaunches

**Comment by millerjp** [comment]
@rgooding what Restart menu option? Could you provide a screenshot please.

**Comment by rgooding** [comment]
This one:

![Screenshot 2024-08-12 at 15 50 08](https://github.com/user-attachments/assets/0282e737-c2c7-4d8c-a91b-ce2dc81c978b)

**Comment by mhmdkrmabd** [comment]
Investigating that

**Comment by mhmdkrmabd** [comment]
Confirmed, thank you @rgooding, working on that

**Comment by mhmdkrmabd** [comment]
Fixed, it should be fine after the next PR
