### ISSUE TITLE
[feat] When deleting a sandbox/local cluster prompt the user if they want to delete the docker compose from the filesystem

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#248]
Thes compose files are being left on the filesystem, users should get a prompt to ask if they want to delete the docker compose

**Comment by mhmdkrmabd** [comment]
@millerjp if you could click the folder icon of the local cluster/cluster/workspace you want to delete; to be sure you're in the right data directory, then try to delete it and see if its folder has also been deleted

https://github.com/user-attachments/assets/8b0bdd1f-4c76-45d8-98cf-6cf1e4684795

**Comment by millerjp** [comment]
@mhmdkrmabd yes, it does that - what i wanted was to make it optional to delete from the file system if possible i.e leave it there for whatever reason the user might want to keep the docker-compose there for other purposes.

**Comment by mhmdkrmabd** [comment]
I see now, I'll add a check box for that - for the local clusters and clusters - which allows to keep the folder in the filesystem
