### ISSUE TITLE
[bug]: Add cluster fields are not cleared after adding a cluster

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#257]
### Do I have the most recent version of AxonOps Workbench installed?

- [x] I am using the most recent beta release

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

13.5.2

### Bug Description

After you add a cluster to the configuration you then try to add a second one. What you see is the fields are already fill out by the previous cluster. 

We should clear all fields after either adding a cluster successfully or cancelling the process.

### Steps to Reproduce

- Add cluster
- Fill in details
- Cancel / Continue
- Select Add Cluster agin

### Expected Behavior

Empty fields

### Actual Behavior

It remembers the previous inputs

### Severity

Medium

**Comment by mhmdkrmabd** [comment]
@digiserg  performed tests on Linux Ubuntu 23, everything works fine - and it should be the same on macOS -

https://github.com/user-attachments/assets/0d57ccd3-4cc2-43a7-a85c-ac304d234f40

If what you mean is when you cancel/close the adding process without proceeding then that's true, and it's a meant behavior; the user might accidentally close the dialog by clicking outside, or he wants to check something in the app before continuing, thus clearing the fields just by closing the dialog won't be efficient, instead, this is happening after a successful addition.
