### ISSUE TITLE
[feat]: Have install of AxonOps for localclusters optional

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#267]
**Is your feature request related to a problem? Please describe.**
Sometimes I dont want to install AxonOps and the overhead on my local system cant cope with the extra load

**Describe the solution you'd like**
When creating a localcluster have it setting up AxonOps optional

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by mhmdkrmabd** [comment]
Working on that, a checkbox will be added to control AxonOps while creating a local cluster

![Image](https://github.com/user-attachments/assets/38a4e1c6-92b9-48de-862a-06552fd5e5f0)

**Comment by mhmdkrmabd** [comment]
@millerjp  now users have the ability to control whether or not AxonOps will be installed within the local cluster
![Image](https://github.com/user-attachments/assets/2d9ff633-d7e0-417c-951e-fdb0ac2d4ef6)

For this change, a new badge has been added to indicate the installation status of AxonOps
![Image](https://github.com/user-attachments/assets/15ef01d6-880c-46eb-8d5d-c617d14630a6)



If AxonOps has been installed within the local cluster, the work area will contain AxonOps as usual:
![Image](https://github.com/user-attachments/assets/d6aa308f-197d-4807-ac90-b85c89faebe5)

In case it hasn't been installed, AxnoOps won't be in the work area:


![Image](https://github.com/user-attachments/assets/f84e58f6-042b-4ae0-af14-27ac8c81e7d0)
