### ISSUE TITLE
[feat]: Add jump to diff button when comparing clusters

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#270]
**Is your feature request related to a problem? Please describe.**
When I have done a cluster diff its hard to find the changes - you have to scroll to find them

**Describe the solution you'd like**
Add a button to jump to next/previous diff

**Describe alternatives you've considered**
Use the changes feature to jump
<img width="388" alt="Screenshot 2024-08-21 at 11 48 22" src="https://github.com/user-attachments/assets/efb5d87b-35e6-4e60-ae75-0aa16e81d342">

**Additional context**
<img width="1893" alt="Screenshot 2024-08-21 at 11 45 44" src="https://github.com/user-attachments/assets/cd6d6f10-065b-4a1e-aac1-d44e20a3b47d">

**Comment by mhmdkrmabd** [comment]
A branch will be created for this feature
