### ISSUE TITLE
[bug]: cqlsh not working

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#282]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

13.5.2

### Bug Description

<img width="384" alt="image" src="https://github.com/user-attachments/assets/47d3366e-3238-4347-bcb8-27e7e3150197">

### Steps to Reproduce

TEST connection

### Expected Behavior

Successful

### Actual Behavior

Error

### Severity

High

**Comment by millerjp** [comment]
It possibly a timeout or something. We can keep an eye and see if we see this again and can reproduce
