### ISSUE TITLE
[bug]: Tracing is very slow

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#285]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

13.5.2

### Apache Cassandra Version(s)

4.1.5

### Bug Description

<img width="1632" alt="image" src="https://github.com/user-attachments/assets/b40edb38-872c-4664-9a1e-8208afbcc021">

I tried running a simple query with tracing enabled but the workbench appears to hang

### Steps to Reproduce

- tracing on;
- select * from keyspace.table;

### Expected Behavior

Query returns rows and I'm able to browse the tracing data

### Actual Behavior

Freeze

### Severity

High

**Comment by digiserg** [comment]
I'm renaming this bug report after further testing. Tracing is working it just takes ages.

**Comment by mhmdkrmabd** [comment]
@digiserg is this happening only on macOS? and is it specific to a table or it's a common behavior? Am tuned for the reply

**Comment by millerjp** [comment]
@digiserg can you manually query the system traces table on your target cassandra cluster and test there to ensure its not an issue with your test cluster. This is working ok for me on Mac

**Comment by digiserg** [comment]
Yes, and it's fine. This is over SSH so it lags a little bit. 

I'm using a 6 node cassandra cluster over a SSH bastion.

https://github.com/user-attachments/assets/580d729f-1d9c-4b75-95fa-56747a1e21fd


https://github.com/user-attachments/assets/fec7ffd0-a626-4a0d-8eb5-ccaba5ccf5ec

**Comment by millerjp** [comment]
I think this is environmental - we can close it for now and reinvestigate if necessary later.
