### ISSUE TITLE
[bug]: link to release notes does not work

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#297]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v0.1.1-internal-20240826

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

13.5.2

### Bug Description

The link does not open the release notes:

![image](https://github.com/user-attachments/assets/72679e41-1d52-421f-921e-06f5d32bfcfa)

### Steps to Reproduce

About -> Release notes

### Expected Behavior

Open chorme with notes

### Actual Behavior

Nothing

### Severity

Low

**Comment by mhmdkrmabd** [comment]
@millerjp  @digiserg  tested on Linux - production mode -, works fine, doing tests on macOS


https://github.com/user-attachments/assets/59c0a7dd-da32-48b0-b652-bd476c847d8b

**Comment by digiserg** [comment]
I just tested again using the latest internal release instead of dev mode and it works fine. You can close this issue @mhmdkrmabd
