### ISSUE TITLE
[feat]: when under a connection workspace i.e connecting to remote clusters (not local clusters) rename text "add clusters" and "refresh connections" to "add connection" and "refresh connections"

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#301]
**Is your feature request related to a problem? Please describe.**
Need to make it cleared that a connection is being added as add cluster could mean something else

**Describe the solution you'd like**
Rename text only on the screen for adding under a connection workspace - leave the text as is when adding local clusters as it makes sense there.

<img width="1280" alt="Screenshot 2024-08-27 at 11 08 29" src="https://github.com/user-attachments/assets/93a79351-a149-49dd-b5ac-24945b04544c">

And rename the add cluster button to be add connection

<img width="882" alt="Screenshot 2024-08-28 at 17 38 46" src="https://github.com/user-attachments/assets/fddc9588-42ba-4e16-aa85-266032ebb937">

**Comment by mhmdkrmabd** [comment]
@millerjp this will change the concept of `clusters` in the app, data folder will be changed to `connections` and many phrases will be changed, it's more sense indeed to change `clusters` to be `connections`. Working on that
