### ISSUE TITLE
[feat]: indicate which fields are optional and mandiatory and validate fields when adding cluster connections

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#302]
**Is your feature request related to a problem? Please describe.**
we need to make sure which fields are optional and manditory when adding cluster connections

<img width="934" alt="Screenshot 2024-08-27 at 11 14 39" src="https://github.com/user-attachments/assets/d9df649b-560d-406c-a545-ea6e7efaed65">

**Comment by mhmdkrmabd** [comment]
@millerjp we just need the host name and ports fields, added a badge to indicate that


![Image](https://github.com/user-attachments/assets/c455cda1-f1c1-4258-aa05-72d16deeda21)

**Comment by mhmdkrmabd** [comment]
@millerjp we just need the host name and ports fields, added a badge to indicate that



![Image](https://github.com/user-attachments/assets/67751944-22ba-440b-a48c-1d6dd9241670)
