### ISSUE TITLE
[feat]: Re-order table information in tree

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#321]
**Is your feature request related to a problem? Please describe.**
When I am browsing table structure in the tree view, I would like to see the items in a better logical order

**Describe the solution you'd like**
Partition Keys, Primary Keys, Clustering Keys,Columns,Options,Triggers

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/user-attachments/assets/fad6e63a-2e69-43cd-98e1-abc9c3da1e14)

**Comment by millerjp** [comment]
This ordering makes more sense, however lets go with 

**Primary Keys, Partition Keys, Clustering Keys, Columns, Options, Triggers**

**Comment by mhmdkrmabd** [comment]
@millerjp @hshimizu 
![Image](https://github.com/user-attachments/assets/e948f40a-8292-43f8-b033-07ee55acadd7)

**Comment by millerjp** [comment]
@mhmdkrmabd looks great 👍
