### ISSUE TITLE
[feat]: Sort columns group alphabetically by name

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#327]
The ordering of columns appears random in the tree - data like this should be sorted predicatbly - alphabetically, asc by name is fine

_Note: the order of primary keys, partition keys and cluster columns groups should be displayed in the natural order they come back as the ordering of these columns is important_

<img width="331" alt="Screenshot 2024-08-29 at 11 25 36" src="https://github.com/user-attachments/assets/d4ea9e5a-e488-401c-80be-d55297545eaf">

**Comment by mhmdkrmabd** [comment]
Implemented
