### ISSUE TITLE
DRM protection does not work on Windows

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#33]

**Comment by mhmdkrmabd** [comment]
@millerjp  the content/DRM protection feature of the app works as expected, worth to be mentioned that this is possible for tools running on the host itself, any external tools - like the one am using to record - will still be able to see and capture the project's window.

![Image](https://github.com/user-attachments/assets/fd619354-e03d-4f1b-a4af-7f50fd85fd9b)

Will close this issue
