### ISSUE TITLE
[bug]: Get CQL Description is not working for indexes

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#330]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240828

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Apache Cassandra Version(s)

N/A

### Bug Description

Right-click on Indexes is not whoing the CQL description.
<img width="328" alt="Screenshot 2024-08-29 at 11 43 08" src="https://github.com/user-attachments/assets/0388275b-5be8-4cc5-a73b-8acb4e1c0565">

Should test this on materialised views also

### Steps to Reproduce

Right click on an index

### Expected Behavior

Should provide option to show CQL description for the index - if possible, also the table CQL its associaed with

### Actual Behavior

Right click does nothing

### Severity

Low

**Comment by mhmdkrmabd** [comment]
@millerjp 


![Image](https://github.com/user-attachments/assets/f4a2d9ca-0e31-4965-a84a-79733664752a)

**Comment by millerjp** [comment]
Looks great @mhmdkrmabd
