### ISSUE TITLE
[bug]: Indexes tree not showing parent table

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#331]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240828

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Apache Cassandra Version(s)

N/A

### Bug Description

When looking at the index tree and seeing indexes, we whould have the table name in the tree somewhere so we know which table it is on.

<img width="328" alt="Screenshot 2024-08-29 at 11 43 08" src="https://github.com/user-attachments/assets/0ec1ee64-e4f0-47d2-a01e-2cee1ca247db">

### Steps to Reproduce

Click on system keyspace -> Indexes to see example
<img width="328" alt="Screenshot 2024-08-29 at 11 43 08" src="https://github.com/user-attachments/assets/c7d8157c-e2c6-4f37-b65e-404bb3e13955">

### Expected Behavior

Show the table name its on

### Actual Behavior

Nothing is displayed

### Severity

Low

**Comment by mhmdkrmabd** [comment]
@millerjp 

![Image](https://github.com/user-attachments/assets/cb14d8be-99dd-4a3e-92de-018c9aa5e030)

**Comment by millerjp** [comment]
looks great @mhmdkrmabd
