### ISSUE TITLE
[bug]: Get CQL description on a table does not return index and materialised view CQL for the table

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#332]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240828

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Bug Description

On tables that have views and indexes we dont see the CQL for them when getting the CQL description of a table

<img width="1038" alt="Screenshot 2024-08-29 at 11 51 57" src="https://github.com/user-attachments/assets/7f8b1cbc-f278-4c98-9147-6d118ff9501b">

### Steps to Reproduce

Right click on a table with an index or view and click Get CQL description eg system.paxos

### Expected Behavior

Expect to see the CQL for the associated view or index in the table CQL description aswell as the table itself

### Actual Behavior

It only displays the table CQL

### Severity

Low

**Comment by millerjp** [comment]
@mhmdkrmabd this is still an issue on latest beta build

**Comment by mhmdkrmabd** [comment]
This should be fine now after merging the PR of the binaries repo, this issue should be closed now
