### ISSUE TITLE
[bug]: Right click CQL description not behaving as expected

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#334]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240828

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Bug Description

Getting the CQL description either hangs or returns the wrong CQL

### Steps to Reproduce

1 - right click on a table to get the CQL description, it shows it
2 - right click on the parent keyspace of the table it sometimes hangs or displays the table
3 - right click on a keyspace before a table and it works

### Expected Behavior

Should show correct CQL

### Actual Behavior

Sometimes hangs, sometimes returns the table i.e the first CQL description returned

### Severity

Low

**Comment by mhmdkrmabd** [comment]
This will be moved to `in review` as it's related to improving the app's performance

**Comment by millerjp** [comment]
Lets clsoe this for now and keey an eye on it
