### ISSUE TITLE
[bug]: table options are not being displayed in tree correctly - missing data

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#338]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240828

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Apache Cassandra Version(s)

5.0-rc1

### Bug Description

<img width="1336" alt="Screenshot 2024-08-30 at 19 43 24" src="https://github.com/user-attachments/assets/d4bac354-f4e4-412e-bd23-0aa253870133">

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Severity

Low

### Further Information

N/A

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
@millerjp  fixed, it was due to a latest change for the `CDC` option

![Image](https://github.com/user-attachments/assets/fcf3b369-fc80-4ffa-ae5e-a3144019ba46)

**Comment by millerjp** [comment]
Thanks @mhmdkrmabd - great!
