### ISSUE TITLE
[feat]: Rename "Edit Workspace" popup to "Workspace Settings"

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#342]
We have different name on the hint and the modal window - makes more sense to call the popup window Workspace Settings to keep it consistent.

<img width="360" alt="Screenshot 2024-09-01 at 07 18 02" src="https://github.com/user-attachments/assets/34cbc093-71ce-46f5-979c-cf0dcbf33819">

Click on it and its called a different name.

<img width="585" alt="Screenshot 2024-09-01 at 07 14 58" src="https://github.com/user-attachments/assets/f6ced08c-7305-41ad-aee1-6041ae5b0ded">

**Comment by mhmdkrmabd** [comment]
Working on that, also checking the tooltips text and their related actions to make sure all phrases are synced

**Comment by mhmdkrmabd** [comment]
Updated

![Image](https://github.com/user-attachments/assets/d99dc6e7-1952-4aaf-9486-8ec1f784e7f3)

![Image](https://github.com/user-attachments/assets/a027ee98-2188-4802-8090-e8ee749b1909)
