### ISSUE TITLE
[feat]: Add system setting to enable/disable CQLSH basic console being displayed in UI

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#343]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Have a system setting defaulting to false (i.e not displayed) on new installs to show/hide the basic CQLSH console and enable/disable the the toggle button

**Additional context**
Once Enhanced CQLSH console is stable and feature complete, we will remove basic CQLSH console completely as an option from the UI - but I would not expect this to be the case to v 1.1+

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
@millerjp Now the basic cqlsh can be controlled via app's settings in the features section
![Image](https://github.com/user-attachments/assets/efc5447b-78ee-4203-aff8-37c9b01c1ae6)

Restarting the app is not required, and actually we can have active connections with basic cqlsh and others without it in the same app's session

Without basic cqlsh
![Image](https://github.com/user-attachments/assets/6cedc7d8-c135-43c4-8a92-63383b61d39c)

With basic cqlsh
![Image](https://github.com/user-attachments/assets/0e1e4ef6-1fb3-4adb-b082-7f73b186bfb5)
