### ISSUE TITLE
[bug]: Cannot update cluster name

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#356]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v0.1.1-internal-20240905

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

13.5.2

### Apache Cassandra Version(s)

4.1.5

### Bug Description

I tried changing the connection name but the "Update Cluster" option is greyed out

![image](https://github.com/user-attachments/assets/e14502f7-0cd8-4453-96a8-33df2a48df4c)

### Steps to Reproduce

Edit an existing cluster and try to change the name

### Expected Behavior

It should allow me to rename it

### Actual Behavior

Update button disabled

### Severity

High

**Comment by millerjp** [comment]
This is because the directoy on the filesystem is the cluster name. The only way to change this would be to rename the directory on the filesystem. Which we could do @mhmdkrmabd ?

**Comment by digiserg** [comment]
User error
