### ISSUE TITLE
[bug]: Dont refresh cluster meta data when executing alter role statements

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#358]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240905

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1

### Apache Cassandra Version(s)

4.1.6

### Bug Description

Under certain circuistances when adding tables, alerting tables etc.. we refresh the cluster meta data to render the tree again. However, we should not be doing this for alter role statements

### Steps to Reproduce

run an alter role statments ane the metadata gets refreshed

### Expected Behavior

does not do this

### Actual Behavior

it refreshes the metadata

### Severity

Medium

**Comment by millerjp** [comment]
Should probably check this for create role also

**Comment by digiserg** [comment]
This is still happening

**Comment by mhmdkrmabd** [comment]
> This is still happening

@digiserg it's appreciated if you provide the statement you've executed

**Comment by digiserg** [comment]
https://github.com/user-attachments/assets/9fb62ca9-4751-4fa5-a0ad-6dba9ec9deed

**Comment by digiserg** [comment]
https://github.com/user-attachments/assets/bfc91db5-b7e8-407c-b366-9afea272b78b

**Comment by mhmdkrmabd** [comment]
Confirmed, will be handled in the next PR

**Comment by mhmdkrmabd** [comment]
Fixed by improve the provided identifiers by the cqlsh tool, tested with different cases:
CREATE => role, user
ALTER => role, user
