### ISSUE TITLE
[bug]: weird directory created in my AxonOps config

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#371]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

1.0.0-beta-20240909

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

13.5.2

### Apache Cassandra Version(s)

4.1.5

### Bug Description

<img width="759" alt="image" src="https://github.com/user-attachments/assets/321815d3-ccf8-4aec-bb32-5966cf5fef4f">

it seems to create a Users/sergio.rua directory

### Steps to Reproduce

```sh
tree ~/.axonops-workbench
```

### Expected Behavior

This directory should not exist

### Actual Behavior

Data in the wrong place

### Severity

Medium

**Comment by mhmdkrmabd** [comment]
@digiserg  the app shouldn't create such a folder, and there's nothing in the code that would do that = perhaps it's an OS thing or and old data -, however, we'll keep an eye on the data folder in the upcoming builds.

This issue will be moved to `in review`
