### ISSUE TITLE
[bug]: grant select is being misinterpreted as select from table 

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#374]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240909

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1

### Apache Cassandra Version(s)

4.1.6

### Bug Description

The enhanced console thinks this is a select from a table

<img width="849" alt="Screenshot 2024-09-09 at 16 21 28" src="https://github.com/user-attachments/assets/120c0d13-8279-4e0f-b348-1db13be86797">

### Steps to Reproduce

run CQL `GRANT SELECT ON ALL KEYSPACES TO rummaan_ro;`

### Expected Behavior

n/a

### Actual Behavior

n/a

### Severity

Medium

**Comment by mhmdkrmabd** [comment]
@millerjp 

![Image](https://github.com/user-attachments/assets/098b752f-fdf7-4d76-98ce-c2081609e9c2)

**Comment by digiserg** [comment]
It looks good

![Image](https://github.com/user-attachments/assets/e100cb36-47af-4c15-adcf-1aa9064c8339)
