### ISSUE TITLE
[bug]: change ordering of history and increase list size plus decrease font size to get more in list

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#383]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240909-01

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Apache Cassandra Version(s)

4.1.6

### Bug Description

Query history is missing queries
<img width="894" alt="Screenshot 2024-09-10 at 12 51 27" src="https://github.com/user-attachments/assets/0f2b707c-869e-4e43-8ea5-e9b73cab2adc">

### Steps to Reproduce

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Severity

Low

**Comment by millerjp** [comment]
actually - this issue here is the order in the scrolling history list. @mhmdkrmabd - update it to have the most recent query first and possibly make the text smaller and allow for a list size of 15 without scrolling so its more obvious

**Comment by mhmdkrmabd** [comment]
Working on that, moved this todo to be for v1.0.0 milestone

**Comment by mhmdkrmabd** [comment]
@millerjp now recent history items are at top, the maximum height has been increased by about 60%, and the maximum allowed items to be stored increased from 30 to 50
![Image](https://github.com/user-attachments/assets/73c5a7e8-bc26-42bc-b97e-9d9c1b136925)
