### ISSUE TITLE
[bug]: sort keyspaces name alphabetically in tree

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#387]
Order now is random - should be in a predictable order.

<img width="278" alt="Screenshot 2024-09-10 at 13 46 05" src="https://github.com/user-attachments/assets/5202f065-317b-402a-afba-29503fd38c62">

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
Before:
![Image](https://github.com/user-attachments/assets/c38a4c18-c70f-4f80-bcd7-6a05c4c594e5)

After:
![Image](https://github.com/user-attachments/assets/43b50ce5-1c6a-4cf8-8f4a-d2a36a7d02be)
