### ISSUE TITLE
[bug]: keyspace name in AxonOps does not match keyspace hame in DB

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#403]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240909-01

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Apache Cassandra Version(s)

4.1.6

### Bug Description

Keyspace is called geetu - but is being show as geet in the tree (tested on Mac and Windows)
<img width="250" alt="Screenshot 2024-09-11 at 16 52 02" src="https://github.com/user-attachments/assets/00ba7e85-905c-4be5-abf0-cd6ea581ae52">
<img width="1441" alt="Screenshot 2024-09-11 at 16 51 53" src="https://github.com/user-attachments/assets/225e3787-8184-4edd-991f-302872b674c9">

### Steps to Reproduce

NA

### Expected Behavior

NA

### Actual Behavior

NA

### Severity

High

**Comment by mhmdkrmabd** [comment]
Fixed, pushed a commit for it
