### ISSUE TITLE
[bug]: Query tracing view shows wrong query with SELECT JSON

### ISSUE THREAD

**Issue by hshimizu** [axonops/axonops-workbench-cassandra#404]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

1.0.0-beta-20240910-01

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows

### Operating System Version

Windows 11

### Apache Cassandra Version(s)

cassandra 4.1.4

### Bug Description

I've enabled tracing and executed S"ELECT * from hayato.hayato;" in the notebook view.

![image](https://github.com/user-attachments/assets/19199369-bba4-44cd-9f57-58860e0c3f32)

Query tracing view for this query shows "Parsing SELECT JSON * from hayato.hayato;"

![image](https://github.com/user-attachments/assets/80f0c4b1-b269-4e39-86e4-5b872df40d5d)

### Steps to Reproduce

1. "tracing on"
2. Execute a query
3. Click on "Trace the query" button

### Expected Behavior

Query in query tracing should reflect the actual query.

Also, I would update the button "Trace the query" to "Show trace"

### Actual Behavior

N/A

### Severity

High

**Comment by millerjp** [comment]
This is not a bug. Its how it works. This is being discussed and planned to be changed.
