### ISSUE TITLE
[bug]: console is broken

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#421]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v0.1.1-internal-20240913-01

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Apache Cassandra Version(s)

4.1.6

### Bug Description

Console is broken - getting corrupt results returned

![Screenshot 2024-09-13 at 14 50 56](https://github.com/user-attachments/assets/e0962eb2-d95a-451e-bf60-ac4acaf4a5bf)

### Steps to Reproduce

run a select

### Expected Behavior

results get returned

### Actual Behavior

corrupt results get returned

### Severity

High

**Comment by mhmdkrmabd** [comment]
Fixed, tested on Linux Ubuntu v22

![Image](https://github.com/user-attachments/assets/68fffb48-5650-473b-bd1a-5d33559dbcc5)
![Image](https://github.com/user-attachments/assets/52e0c52e-5b5a-48fc-98a3-3044424df824)

**Comment by mhmdkrmabd** [comment]
Tested on Windows 10

![Image](https://github.com/user-attachments/assets/72aa3d6d-6fbd-4b12-9a19-6ebd1c422f63)
![Image](https://github.com/user-attachments/assets/15b9945b-5de7-4f9f-bc89-7c1a8c293923)

**Comment by digiserg** [comment]
Tested and fixed on `0.1.1-internal-20240916-01`
