### ISSUE TITLE
[bug]: JS error on dmg install with 1.0.0-beta-20240917-02

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#436]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

1.0.0-beta-20240917-02

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Apache Cassandra Version(s)

N/A

### Bug Description

<img width="563" alt="Screenshot 2024-09-18 at 08 04 32" src="https://github.com/user-attachments/assets/b83d80e5-2fcf-46e2-941c-f0f04c6c0927">

```
Uncaught Exception:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Applications/AxonOps Workbench.app/Contents/Resources/app.asar/node_modules/ansi-styles/index.js from /Applications/AxonOps Workbench.app/Contents/Resources/app.asar/node_modules/slice-ansi/index.js not supported.
Instead change the require of /Applications/AxonOps Workbench.app/Contents/Resources/app.asar/node_modules/ansi-styles/index.js in /Applications/AxonOps Workbench.app/Contents/Resources/app.asar/node_modules/slice-ansi/index.js to a dynamic import() which is available in all CommonJS modules.
at c._load (node:electron/js2c/node_init:2:17025)
at require (/Applications/AxonOps Workbench.app/Contents/Resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
at Object.<anonymous> (/Applications/AxonOps Workbench.app/Contents/Resources/app.asar/node_modules/slice-ansi/index.js:4:20)
at Module._compile (/Applications/AxonOps Workbench.app/Contents/Resources/app.asar/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
```

### Steps to Reproduce

Install latest beta and launch

### Expected Behavior

N/A

### Actual Behavior

N/A

### Severity

High

**Comment by digiserg** [comment]
It should be fixed on https://github.com/axonops/axonops-workbench-cassandra/releases/tag/1.0.0-beta-20240918-01
