### ISSUE TITLE
[bug]: No option to save schema metadata json

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#441]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v1.0.0-beta-20240918-01

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

14.6.1 (23G93)

### Apache Cassandra Version(s)

5.0

### Bug Description

I have connected to a local cluster DB for the first time and want to save the JSON - there is no option to do this?
<img width="1710" alt="Screenshot 2024-09-20 at 08 03 12" src="https://github.com/user-attachments/assets/987ffae3-916a-4bae-a238-17fb02e498f3">

### Steps to Reproduce

Deplot a local cluster, click on  schema diff and there is no button to save the current state anywhere

### Expected Behavior

There should be a button allowing users to save the snapshot

### Actual Behavior

no option is available

### Severity

High

**Comment by mhmdkrmabd** [comment]
This is not a bug but meant to be like this; as local clusters are considered to be a sandbox, however, we can enable saving snapshots for local clusters

**Comment by mhmdkrmabd** [comment]
@millerjp 
![Image](https://github.com/user-attachments/assets/f0b22059-c86f-4ccc-94f9-104dc2baaeea)
