### ISSUE TITLE
[bug]: Can't save templated variables to use in cqlshrc

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#447]
### Do I have the most recent version of AxonOps Workbench installed?

- [X] I am using the most recent beta release

### AxonOps Workbench Version

v0.1.1-internal-20240923

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

MacOS

### Operating System Version

13.5.2

### Apache Cassandra Version(s)

4.1.5

### Bug Description

I'm trying to add the variable SSL_CERTIFICATE to the settings
<img width="839" alt="image" src="https://github.com/user-attachments/assets/16f73f9b-6420-4659-9f85-351831b497b0">

### Steps to Reproduce

Just try to add it

### Expected Behavior

It should save the variable and be used by cqlsh

### Actual Behavior

Error

### Severity

Low

**Comment by millerjp** [comment]
@mhmdkrmabd can you also test the templated substitutions in the cqlshrc file before commiting as I have a feeling this might not work...

**Comment by mhmdkrmabd** [comment]
@millerjp @digiserg 
> Some settings have been successfully saved, however, an error has occurred with variables, Variable or more are not having a valid name or value, make sure unique names and values are provided for each variable and **the variable name is only digits and letters**.
