### ISSUE TITLE
[feat]: Ask user before stopping docker

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#451]
**Is your feature request related to a problem? Please describe.**
When using the sandbox the CLOSE button at the top corner closes the workspace and stops docker. 

The feedback from the users if they would like to have a confirmation prompt to ask whether docker should be stopped.

**Describe the solution you'd like**
Add a prompt and ask for confirmation before stopping docker

**Comment by millerjp** [comment]
@digiserg no - we wont do this. Users can manage that themselves and there is a lot of complexity around how the spawned processes work in relation to windows and mac. We are not changing this now.
