### ISSUE TITLE
Frequent disconnects

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#59]
I'm seeing frequent disconnects from the sandbox even though it's all running fine and I don't experience any issues.

Also, the text message can probably be rephrased for clarity.  The disconnect error message mentions *a toast* which may not be clear as to what it refers to.

![image](https://github.com/axonops/axonops-workbench-cassandra/assets/58211930/feb05557-9c0a-4e12-8d62-03aa28d5e01a)

**Comment by millerjp** [comment]
This seems to have been fixed in latest build
