### ISSUE TITLE
Fix code scanning alert - Incomplete string escaping or encoding

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#70]
Tracking issue for:
- [ ] https://github.com/axonops/axonops-workbench-cassandra/security/code-scanning/2

**Comment by mhmdkrmabd** [comment]
This issue can be ignored, won't cause any problems in the project, it has been found in `jquery-ui` library and it's about an encoding process that doesn't affect the main processes, the alert will be dismissed
