### ISSUE TITLE
[feat] Include application build number and distribution in about section

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#83]
We need to display the build and version number in the About section - its particualry needed for testing purposes

@digiserg you will need to generate this as part if the pipeline

**Comment by millerjp** [comment]
Add a section here with as much information as you can - including git tags or whatever we need to know what this build relates to. Make sure to include the cqlsh component also.

<img width="1244" alt="Screenshot 2024-07-11 at 15 49 14" src="https://github.com/axonops/axonops-workbench-cassandra/assets/163300/1ba21494-6d7c-4cd4-98d7-15b1e96a5156">

**Comment by millerjp** [comment]
Make sure there is a link to the github projects tagged code eg
https://github.com/axonops/axonops-workbench-cassandra/tree/0.1.0-beta1-rc1

And its on both axonops-workbench-cassandra and https://github.com/axonops/axonops-workbench-cqlsh

@mhmdkrmabd I want the users to be able to click on this link and it opens a browser directly to the code and the specific tag

**Comment by mhmdkrmabd** [comment]
Will collaborate with @digiserg to work on that

**Comment by digiserg** [comment]
I can get it from the About menu already
