### ISSUE TITLE
cqlsh binaries should not be placed in .axonops-developer-workbench folder in users home directory - these should be bundled in the application

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#87]
<img width="410" alt="Screenshot 2024-07-11 at 17 22 47" src="https://github.com/axonops/axonops-workbench-cassandra/assets/163300/3a2cf98b-2e12-4a38-9e29-7e67776a74f6">

        ├── cqlsh-407
        ├── cqlsh-410
        └── keys_generator

These should not be here

**Comment by mhmdkrmabd** [comment]
Working on that, this will indicate changes in the related part of the building process in the `package.json` file

**Comment by digiserg** [comment]
![image](https://github.com/user-attachments/assets/d97b3f4c-5855-41f8-a8db-a03774541489)

The data path for Windows is probably wrong also. Windows does not use `.directory` syntax. Can you look into this also?

**Comment by mhmdkrmabd** [comment]
Updated, now on Windows the folder won't have a dot prefix
