### ISSUE TITLE
localisation files should not be in the .axonops-developer-workbench directory - they should be bundled in the application

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#88]
<img width="410" alt="Screenshot 2024-07-11 at 17 22 47" src="https://github.com/axonops/axonops-workbench-cassandra/assets/163300/f85bf92b-248a-4c43-8582-391219966ebd">

**Comment by mhmdkrmabd** [comment]
I believe putting those files outside the application's root folder will help the user add new files or edit the existing ones as needed, we can add new languages with ease by following the file's structure, and the app is capable of reading all valid JSON files in the localization folder and treat them as languages references

**Comment by millerjp** [comment]
@mhmdkrmabd no - we would have a new release to support updates or new languages. This would never be maintained by users. Please move it to the application folder.

**Comment by mhmdkrmabd** [comment]
Got it, working on that
