### ISSUE TITLE
contentProtection should be in the keychain/registry and only editable if users have admin rights

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#90]
If you store this in a json file in the users home directory it is editable - the point of this setting is to enable or disable the DRM and needs to be protected and only editable by **admin users** on the OS. 

<img width="410" alt="Screenshot 2024-07-11 at 17 22 47" src="https://github.com/axonops/axonops-workbench-cassandra/assets/163300/58959095-a78e-4117-89bb-bddefa9e85e9">

(base) ➜  config cat app-config.cfg
[security]
contentProtection=false
loggingEnabled=false
cassandraCopyrightAcknowledged=true

[ui]
theme=light
language=en

[limit]
sandbox=1
cqlsh=10

[sshtunnel]
readyTimeout=60000
forwardTimeout=60000

**Comment by mhmdkrmabd** [comment]
Related to issue #36 , it'll be moved to another place rather than the config file
