### ISSUE TITLE
Storing the references to varaibles in variables.json is not safe

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#91]
<img width="410" alt="Screenshot 2024-07-11 at 17 22 47" src="https://github.com/axonops/axonops-workbench-cassandra/assets/163300/c216413d-c6a7-4d7a-909e-1997d6108802">

And the contens of variables.json

<img width="373" alt="Screenshot 2024-07-11 at 17 33 31" src="https://github.com/axonops/axonops-workbench-cassandra/assets/163300/2fa420d4-8305-4752-aec1-32c0287f9620">

The problem with storing this here is if I delete this file in my home directory, then the values will remain in the keychain forever. We need to store these pointers in such a way that they are discoverable in the keychain eg store the JSON in the keychain and manage it there instead of on the file system,

**Comment by mhmdkrmabd** [comment]
Working on that

**Comment by mhmdkrmabd** [comment]
Now the manifest and the values are stored in the OS keychain
