### ISSUE TITLE
The progress dialog box can block the AI view

### ISSUE THREAD

**Issue by millerjp** [axonops/axonops-workbench-cassandra#95]
<img width="683" alt="Screenshot 2024-07-11 at 18 34 58" src="https://github.com/axonops/axonops-workbench-cassandra/assets/163300/29358f49-71ce-46d3-88a2-f8bc38a5cf9a">

We need way to move this or minimise it when it blocks the AI view

**Comment by mhmdkrmabd** [comment]
@millerjp 


![Image](https://github.com/user-attachments/assets/20b005aa-9347-438b-81c0-eb6baa3e40e9)
