### ISSUE TITLE
Workspaces are not properly deleted

### ISSUE THREAD

**Issue by digiserg** [axonops/axonops-workbench-cassandra#96]
1. Create a workspace
2. Configure a cluster
3. Test & Connect
4. Exit and delete the cluster & workspace
5. Create another workspace using the *same* name as before
6. When you try to create a cluster, the details are already filled from the previous instance

**Comment by mhmdkrmabd** [comment]
This is not an issue but how the app behaving by default, even if the user has deleted a workspace and created another with different name he'll find the previous data he has filled to create a cluster, however, this will be changed; the fields will be cleared after a successful cluster adding/updating process.

**Comment by mhmdkrmabd** [comment]
Working on that. After a successful add/update process for both; workspace and cluster, fields in the each related dialogs will be cleared
